### PR TITLE
Add squeeze option to nn.Sum

### PR DESCRIPTION
**Pull request by DmitryUlyanov**
It is sometimes inconvenient, that nn.Sum squeezes the dimension it sums over while torch.sum does not. This adds additional option to make nn.Sum not squeeze the output tensor. Squeezed as before by default for compatibility.

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@DmitryUlyanov Can you add a unit test and update the documentation?

**Comment by DmitryUlyanov** [comment]
Yeah, I will.

**Comment by nicholas-leonard** [comment]
@DmitryUlyanov Soon? XD

**Comment by DmitryUlyanov** [comment]
Sorry :) Done.

**Comment by gchanan** [comment]
btw, we recently added a "keepdim" parameter to torch.sum (see e.g. https://github.com/torch/torch7/commit/c5e5487075fa7c9bafcbdc9d52e114aedb2bdac3).  It's currently default to True at the lua, python, C levels, but we may change the python default in the future.

I don't know how you want to deal with this in this commit, just pointing it out.

**Comment by nicholas-leonard** [comment]
@DmitryUlyanov Merged and rebased at https://github.com/torch/nn/commit/44a15a1acbe1965364585b21371a795bfe593955 . Thanks!

**Pull request closed without merging**
