### PR TITLE
Update simple.md

### PR DESCRIPTION
**Pull request by Atcold**
Fixed the hell out of the indentation and formatting.
New lines do not affect *GitHub* rendering but it does affect command-line doc, so **DO NOT USE CARRIAGE RETURN**.

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
You are going to need to modify a lot of markdown docs to remove all the carriage returns.

**Comment by nicholas-leonard** [comment]
Anyone know if we could instead modify the [dok](https://github.com/torch/dok) packages such that it erases carriage returns automatically when generating TREPL doc?

**Comment by soumith** [comment]
ugh, sorry i did not merge this earlier, but there are merge conflicts now. can i haz a resolve?

**Comment by Atcold** [comment]
How do I solve them, @soumith?

**Comment by soumith** [comment]
Just rebase with master.

**Comment by Atcold** [comment]
I fixed all merging conflicts, but now there are all this commits in the way! O gosh!

**Comment by Atcold** [comment]
The merging conflicts were due to removed trailing spaces.
Could possibly people have a check on whether they add extra trailing spaces to code and documentation? My editor, by default, eats every trailing space, so it avoids creating conflicts.

**Comment by soumith** [comment]
thanks Alfredo. My editor at some places does, but some places it lets trailing spaces be. it's weird.

**Comment by Atcold** [comment]
One question. What I've done (and it took me forever) has been `git reset --hard torch/master` on my `patch-3` and then `git cherry-pick myDocFix` and then `git push --force`.

**Comment by soumith** [comment]
git pull --rebase

it's like magic! and it does the same as what you have done.

**Comment by Atcold** [comment]
Thank you @soumith, [here](http://gitready.com/advanced/2009/02/11/pull-with-rebase.html) there's a nice article from *git read* about it. I guess it's worth it reading it.

**Pull request merged**
