### PR TITLE
LeakyReLU

### PR DESCRIPTION
**Pull request by rotmanmi**
Hi,

I've added a LeakyReLU module for nn.

Best,

Michael.

### CODE REVIEW

**Comment by szagoruyko** [comment]
Nice PR, thanks! here is a shorter one though:
```lua
local LeakyReLU, parent = torch.class('nn.LeakyReLU', 'nn.PReLU')

function LeakyReLU:__init(p)
  parent.__init(self)
  self.weight:fill(p)
  self.gradWeight:fill(0)
end

function LeakyReLU:__tostring__()
  return torch.type(self) .. string.format('(%g)', self.weight[1])
end

function LeakyReLU:accGradParameters(input, gradOutput, scale)
end

function LeakyReLU:zeroGradParameters()
end

function LeakyReLU:updateParameters(learningRate)
end
```

**Comment by rotmanmi** [comment]
I think PReLU is not done inplace.

**Comment by szagoruyko** [comment]
it is better to add inplace option to PReLU then

**Comment by rotmanmi** [comment]
well, PReLU allows for negative derivative on the negative side and then
you cannot use it inplace. as this is dynamical, you cannot choose it
beforehand.

**Comment by soumith** [comment]
@rotmanmi this looks fine. there are some merge conflicts, and the commits have to be squashed.

**Comment by soumith** [comment]
I see you've opened https://github.com/torch/nn/pull/409/files , closing this then...

**Pull request closed without merging**
