### PR TITLE
nn.readthedocs.org

### PR DESCRIPTION
**Pull request by nicholas-leonard**
These changes will give you this : http://nn.readthedocs.org/en/readthedocs/index.html . Users will need to update dok as well.

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
@clementfarabet @andresy @soumith @koraykv If you guys like the idea of setting up a readthedocs documentation site, then I will proceed to do the same with torch, image, and so on. It shouldn't change any of the look and feel of the github docs. However, if we do decide to move to readthedocs, all the inter-repo hyperlinks will need to point to readthedocs instead of github. So basically, waiting for your approval to go forward with this migration of docs to readthedocs.org.

**Comment by andresy** [comment]
Just curious: there is no way do to this with relative paths, somehow? It would be nice if one could also read the doc offline. In any case, I think it is nicer like this, thanks!

**Comment by nicholas-leonard** [comment]
@andresy You can use relative paths within a repository. But I know of no way to keep the links between different repositories relative (so that the github ones point to github, and the readthedocs ones point to readthedocs).

**Comment by hughperkins** [comment]
That looks quite nice :-)

**Comment by soumith** [comment]
this looks quite cool nick!

**Pull request merged**
