### PR TITLE
Module:listModules()

### PR DESCRIPTION
**Pull request by nicholas-leonard**
This PR includes doc and unit tests. The method has already been used for nn.Recurrent in nnx.

### CODE REVIEW

**Comment by soumith** [comment]
there is a "for_each" submitted in this PR https://github.com/torch/nn/pull/149
That is probably going to be merged, making this redundant.

That will mostly be renamed to :apply, just like in nngraph, and torch tensors.

**Comment by andresy** [comment]
we have here and there things in torch which implement :totable() ... should it be that here?

**Comment by nicholas-leonard** [comment]
It isn't the same as for_each nor apply which takes a callback. This method is already used in nn.Recurrent which I intend to transfer from nnx to nn. I don't see why we could have both for_each and listModules? They have different uses in mind. listModules is more like parameters() where a flattened list of modules (instead of parameters) is returned.

**Comment by soumith** [comment]
okay great. how do you feel about :listModules -> :totable()

**Comment by nicholas-leonard** [comment]
To me totable() is more ambiguous than listModules(). Like, what exactly is totable? modules, parameters, outputs? But if you insist, I can take the time to change the nn.Recurrent code to use totable() instead.

**Comment by soumith** [comment]
thanks!

**Pull request merged**
