### PR TITLE
Adds Exponential Linear Unit (ELU)

### PR DESCRIPTION
**Pull request by lukasc-ch**
This should add the ELU unit, for which already a pull request exists (#500), however with C implementation and documentation, i.e. replacing the previous pull request. A CUDA implementation will follow. This is my first pull request here, so let me know if I am violating some rules.

### CODE REVIEW

**Comment by lukasc-ch** [comment]
The pull request for the cuda implementation is torch/cunn#169

**Comment by lukasc-ch** [comment]
I have closed and opened the PR twice now to force the CI stuff to rebuild my module. Always one of the confiugrations fails to pass the tests, always with an error unrelated to the PR. Any idea why?

**Comment by lukasc-ch** [comment]
I have closed and opened the PR twice now to force the CI stuff to rebuild my module. Always one of the confiugrations fails to pass the tests, always with an error unrelated to the PR. Any idea why?

**Comment by soumith** [comment]
Thanks Lucas, nicely done.

**Pull request merged**
