### PR TITLE
Add support for negative dimension and both batch and non batch inputs in nn.Min, nn.Max and nn.Mean

### PR DESCRIPTION
**Pull request by vgire**
This completes https://github.com/torch/nn/pull/463 for nn.Mean, nn.Min and nn.Max

### CODE REVIEW

**Comment by soumith** [comment]
That was nice. (And really quick!). Can I request you to squash your commits before I merge it in...

**Comment by szagoruyko** [comment]
I think _getPositiveDimension function should be moved to utils.lua

**Comment by vgire** [comment]
@soumith Sorry for that. Done now.
@szagoruyko I agree. This function was taken from `nn.SplitTable` so it might be used elsewhere in `nn`. Since I am still new to torch an `nn`, I don't feel I can propose this kind of refactoring.
On the same note, tests for `nn.Sum`, `nn.Mean`, `nn.Min` and `nn.Mean` could be refactored.

**Comment by vgire** [comment]
Do you need something else to merge this PR ?
Do you want me to move `_getPositiveDimension` from `nn.Sum`, `nn.Mean`, `nn.Min`, `nn.Max` and `nn.SplitTable` to utils.lua ?

**Comment by soumith** [comment]
I'm very sorry for the delay in merging this. A bunch of conference deadlines conspired against me being responsive. Reviewing it now.

**Comment by soumith** [comment]
Thanks a lot for the contribution.

**Pull request merged**
