### PR TITLE
Fix output sizes in dilated convolution docs.

### PR DESCRIPTION
**Pull request by jonathantompson**
See line 44 of SpatialDilatedConvolution.c

```
long outputHeight = (inputHeight + 2*padH - (dilationH * (kH - 1) + 1)) / dH + 1;
```

The formula in the doc now matches.

### CODE REVIEW

**Comment by soumith** [comment]
thanks jono!

**Comment by jonathantompson** [comment]
Bloody hell that was fast.  Are you just continuously refreshing the PR tab? :-)

**Comment by soumith** [comment]
I'm not me I'm someone else. also, you still haven't switched to TF. it's been one year. ;-)

**Comment by jonathantompson** [comment]
I have switched to TF. I just like reading torch docs in my free time :-)

**Pull request merged**
