### PR TITLE
Allowing Narrow to be agnostic to input type.

### PR DESCRIPTION
**Pull request by clementfarabet**
Is this reasonable? We have a use case where we need to accept LongTensors as inputs.

### CODE REVIEW

**Comment by hughperkins** [comment]
That's interesting. Cannot convert network modules to long or int?
```
th> a = nn.Narrow(1,2,3)
                                                                      [0.0000s]
th> a.gradInput
[torch.DoubleTensor with no dimension]

                                                                      [0.0002s]
th> a:float()
nn.Narrow
                                                                      [0.0003s]
th> a.gradInput
[torch.FloatTensor with no dimension]

                                                                      [0.0001s]
th> a:long()
[string "_RESULT={a:long()}"]:1: attempt to call method 'long' (a nil value)
stack traceback:
	[string "_RESULT={a:long()}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/user/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670	
                                                                      [0.0002s]
th> a:int()
[string "_RESULT={a:int()}"]:1: attempt to call method 'int' (a nil value)
stack traceback:
	[string "_RESULT={a:int()}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/user/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670	
                                                                      [0.0002s]
th> a:byte()
[string "_RESULT={a:byte()}"]:1: attempt to call method 'byte' (a nil value)
stack traceback:
	[string "_RESULT={a:byte()}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/user/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
	...user/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670	
                                                                      [0.0002s]
th> 
```

**Comment by soumith** [comment]
@hughperkins nope, we only fundamentally added Float Double and CUDA support. One has to choose the battles he fights :)

**Comment by hughperkins** [comment]
> One has to choose the battles he fights :)

Hmmm, right :-)

**Comment by clementfarabet** [comment]
We could definitely add shortcuts like :long(), :int(), ... for now it's doable by calling the full operator: 
module:type('torch.LongTensor'). A bit verbose :-).

**Comment by nicholas-leonard** [comment]
@clementfarabet yeah that is what I do. I would be nice to have a `long()`, `int()` shortcut though.

**Pull request merged**
