### PR TITLE
Add Volumetric Dilated Max Pooling

### PR DESCRIPTION
**Pull request by kmul00**
`VolumetricDilated Max Pooling`.
Made sure API of `VolumetricMaxPool` remains consistent.

new file:   VolumetricDilatedMaxPooling.lua
modified:   init.lua
modified:   lib/THNN/generic/THNN.h
copied:     lib/THNN/generic/VolumetricMaxPooling.c -> lib/THNN/generic/VolumetricDilatedMaxPooling.c
modified:   lib/THNN/generic/VolumetricMaxPooling.c
modified:   lib/THNN/init.c
modified:   test.lua

### CODE REVIEW

**Comment by kmul00** [comment]
The tests pass well and good in my system. And in Travis also it fails in one case. 
Maybe I am missing some corner case, not sure.

**Comment by soumith** [comment]
Thanks Koustav!

**Comment by soumith** [comment]
There is indeed a corner case bug. Can you look into it when you get a chance.

**Comment by kmul00** [comment]
@soumith Yeah there was. In [this line](https://github.com/torch/nn/pull/943/files#diff-da0328dca4f40e946c4c274b8422a3ceR168). 
I fixed it and squashed the commit.

Is there something else as well ?
If yes, I will have a look at it.

**Comment by soumith** [comment]
no i think that's it, but i already merged this PR before you squashed and fixed. Can you send another PR rebased on master.

**Comment by kmul00** [comment]
But the commit which you merged seems to have it fixed. Here : https://github.com/torch/nn/commit/b56f0c0536c1943387529d30d0dba5f679025af9

Anyways, just to be safe, I will rebase and send another PR.

**Comment by kmul00** [comment]
Hi @soumith ,

I just cloned the latest `nn` repo, and the mistake is no longer there. It's not a problem any more, I suppose. :)

**Comment by soumith** [comment]
ok cool :)

**Pull request merged**
