### PR TITLE
cmake: add soversion for libTHNN.so

### PR DESCRIPTION
**Pull request by CDLuminate**
This change is imported from Debian package.

### CODE REVIEW

**Comment by fmassa** [comment]
This change *as is* won't work with `ffi`.
We discussed about it in the `gitter` channel https://gitter.im/apaszke/THNN on August 5, but we have not yet reached an agreement on this.

**Comment by CDLuminate** [comment]
@fmassa I took a look on that gitter history, and do you mean that this change might bring unexpected result to OS X users although it works for linux users?

**Comment by fmassa** [comment]
@CDLuminate This change broke the build for half of the systems in Travis (which are running in Linux), check the history.

**Comment by soumith** [comment]
because package.cpath is usually ?.so and not ?.dylib etc.
You cannot change it from MODULE to SHARED

**Comment by CDLuminate** [comment]
I'll look into it later.

**Pull request closed without merging**
