### PR TITLE
fix condition logic for coef recalculation in SpatialSubtractiveNormalization

### PR DESCRIPTION
**Pull request by elikosan**
Existing conditional expression always verified, resulting in overhead as coefficients were recalculated every time. Fix and simplify expression by using cached input size.

### CODE REVIEW

**Comment by soumith** [comment]
this will fail if input size changes right? that's not correct.

**Comment by elikosan** [comment]
If the input size changes, then it will recompute the coefs.
The expression: not input:isSize(self._inpsz) becomes true when the size of input and the cached size are different.

**Comment by soumith** [comment]
thanks!

**Comment by elikosan** [comment]
Hi Soumith,

I found out why Travis failed.
I need to clear my cache in SpatialSubtractiveNormalization:clearState()
Otherwise the jac.TestIO fails

I will make another pull request with the fix.
Sorry about that.

Eric.

**Pull request merged**
