### PR TITLE
Fix output formula in SpatialDilatedConvolution

### PR DESCRIPTION
**Pull request by ankitvgupta**
Fixed a small typo in the output width and height formulas in SpatialDilatedConvolution.

 "+" should be a "-"

### CODE REVIEW

**Comment by fmassa** [comment]
I'm not sure this fix is right.
The formula in the documentation seems to be consistent with what is computed in the C code, as seen [here](https://github.com/torch/nn/blob/master/lib/THNN/generic/SpatialDilatedConvolution.c#L46-L47).

**Comment by ankitvgupta** [comment]
Hey @fmassa 

I believe there are an extra set of parentheses in the C version.

**Comment by ankitvgupta** [comment]
No problem! Let me know if there is anything else I need to do to get this merged (first time contributing).

**Comment by soumith** [comment]
Thanks Ankit

**Pull request merged**
