### PR TITLE
Adding Fractional Max Pooling

### PR DESCRIPTION
**Pull request by soumith**
Implemented by @wickedfoo

Code + Tests + doc

CUDA version incoming as well.

### CODE REVIEW

**Comment by soumith** [comment]
From paper "Fractional Max Pooling" by Ben Graham : arxiv.org/abs/1412.6071

**Comment by soumith** [comment]
cc: @btgraham

**Comment by jonathantompson** [comment]
Ohh, what's this!  Is this the FB secret sauce? :-)

**Comment by soumith** [comment]
Haha no it's a nice paper by ben Graham, read it. It gets rid of cycling effects, like applying dithering on the pixel quantization.

**Pull request merged**
