### PR TITLE
Padding in the middle

### PR DESCRIPTION
**Pull request by csbrown**
This updates the Padding module so that padding can be inserted at any index along the specified dimension.  It is totally backwards compatible, so you can still call it just like before, and it will work just like before, preserving contiguity insomuch as the previous version did.

The addition is an extra optional parameter called [index] into which you can specify the index at which to pad.  If padding it negative, index counts from the left, if padding is positive, it counts from the right.

I needed to put some zeros in the middle of a Tensor, and this seemed like the best way to do it.

### CODE REVIEW

**Comment by soumith** [comment]
update the documentation with this new option

**Comment by soumith** [comment]
closed the PR by mistake, sorry.

**Comment by csbrown** [comment]
docs updated.

**Comment by Atcold** [comment]
@csbrown, I think you should squash the commits, so that @soumith is going to be happy to merge :grimacing:

**Comment by csbrown** [comment]
rebased.

**Comment by Atcold** [comment]
@csbrown, can you change
`module` = `nn.Padding(dim, pad [, nInputDim, value, index])`
to
```lua
module = nn.Padding(dim, pad [, nInputDim, value, index])
```
The first is the old style, the second is the new one.

**Comment by csbrown** [comment]
k

**Comment by soumith** [comment]
Everything looks good on the code side, but please add test cases to test.lua for the index option.
They provide sanity checks testing the backward gradients against finite difference approximations.

**Comment by soumith** [comment]
as soon as you add the test cases, and they pass, this is good for merge.

**Comment by csbrown** [comment]
Added the index option to the Padding test.  The previous test cases were randomized, so I stuck with that paradigm.  Ran the test 1000 times, and there were no errors, so it is highly unlikely that the module is incredibly broken.

**Comment by soumith** [comment]
Thank you!

**Comment by csbrown** [comment]
First Pull Request = Accepted.  woot woot!  Thanks for your patience, @soumith && @Atcold.

**Pull request merged**
