### PR TITLE
Use stable loss and gradient for MultiLabelSoftMarginCriterion

### PR DESCRIPTION
**Pull request by arunmallya**
This replaces the earlier MultiLabelSoftMarginCriterion consisting of a Sigmoid, followed by a BCE for loss and gradient computation. The earlier structure led to instability due to numerical precision. 

The new code combines these two steps and uses a more stable form of the loss and gradient.

This addresses issue **https://github.com/torch/nn/issues/949**.

### CODE REVIEW

**Comment by soumith** [comment]
hi arun, i see that you completely ignored the "weights" parameter in the new implementation :)
hope that's not an oversight...

**Comment by arunmallya** [comment]
Oh, my bad. Will add that in.

**Comment by soumith** [comment]
@arunmallya i want to get this PR to completion. Would you have time to finish it? If not I can take it over...

**Comment by arunmallya** [comment]
Would greatly appreciate if you could take over. I am a bit tied up with CVPR at the moment. Thanks!

**Comment by ayumiymk** [comment]
the source doesn't update?

**Comment by nicholas-leonard** [comment]
@ayumiymk I added some unit tests for weights and made it more efficient by reusing buffers. Thanks for the PR!

**Pull request merged**
