### PR TITLE
Add correctness test on SparseLinear in multithreaded case (and remov…

### PR DESCRIPTION
**Pull request by nkoumchatzky**
…e trailing whitespaces).

Actually, I'm testing that this test works in the OpenMP + BLAS setup. It works with OMP_NUM_THREADS=1 and MKL, fails with OMP_NUM_THREADS > 1 and MKL, just want to test the CI build here.

If you want to convince yourself the test should work, run it with OMP_NUM_THREADS=1 at home!

### CODE REVIEW

**Comment by nkoumchatzky** [comment]
Ok, it looks like all the tests fail with OpenMP + OpenBlas. This is likely due to the accGradParameters function using OpenMP at the higher loop level, which allows for concurrent unprotected gradWeight updates if the same indices are found within the input. It seems it was wrong before too.

**Comment by soumith** [comment]
cc: @ebetica

**Comment by soumith** [comment]
there are now correctness tests and fixes via https://github.com/torch/nn/pull/811/files

**Comment by nkoumchatzky** [comment]
Thanks @soumith!

**Pull request closed without merging**
