### PR TITLE
More broken compatibility with cutorch 1.0

### PR DESCRIPTION
**Pull request by mys007**
This extends https://github.com/torch/nn/pull/979

### CODE REVIEW

**Comment by soumith** [comment]
this is broken. torch.cudaLong does not really exist. Check for torch.CudaLongTensor instead

**Comment by soumith** [comment]
See https://github.com/torch/nn/commit/0a0c589dfe7ca696316e1deccfe483ed45ab930e

**Comment by mys007** [comment]
I'm really sorry for the introduced bug. I've fixed this PR.

**Comment by soumith** [comment]
Thanks!

**Pull request merged**
