### PR TITLE
WIP: R-op

### PR DESCRIPTION
**Pull request by bartvm**
This is some preliminary code for the R-op in Torch. Currently only the Linear, Tanh and Sigmoid modules are implemented, but it should be relatively straightforward to implement new modules. Making a PR to get some feedback, since there was some interest (#397), but it needs some work before it's actually in a useful state.

I compared the results to Theano for correctness.

### CODE REVIEW

**Comment by cswhjiang** [comment]
@bartvm I wrote some testing code based on the rop.lua. I found an weird result. The code is [here](https://gist.github.com/cswhjiang/dc9be98c0963b3124d8c). If we use ````clone````, the norm of Hv2 is always 0. If we use ````copy````, the norm of Hv2 is correct. Is there a bug? Or I wrote the wrong code?

**Comment by bartvm** [comment]
Without having looked too closely at the code, I think that `rParameters2:copy(rParameters_backup)` and  `rParameters2 = rParameters_backup:clone()` do very different things. With `copy` you copy the contents of `rParameters_backup` into `rParameters2`, modifying the latter (which is what you want). By calling `clone` on the other hand, you actually create an entirely new tensor and assign that to the Lua variable name `rParameters2` i.e. you create an entirely *new* `rParameters2` variable, leaving the old one empty (filled with zeros).

**Comment by cswhjiang** [comment]
@bartvm Thanks for your response. I figured it out just now.

**Comment by bartvm** [comment]
Just a note that the latest modules implemented by @cswhjiang should probably be tested against e.g. Theano to make sure that they are correct.

**Comment by andresy** [comment]
Bart, note that you could create a package nnrop where you have a file per nn module (as in nn) and where you define these additional methods in there (the class system allows you to add methods). This way a "require 'nnrop'" would define those additional methods, and the definitions would be cleaner compared to have them in a unique big file.

**Comment by bartvm** [comment]
@andresy Sure, I initially started with mirroring the approach from `hessian.lua`, but I agree that a separate package would be cleaner.

**Comment by andresy** [comment]
yes, i somehow missed the hessian case (i actually did my own package for this at some point), but i think it should also be the same :)

**Pull request closed without merging**
