### PR TITLE
THNN functional module conversions batch 5 (Volumetric*)

### PR DESCRIPTION
**Pull request by andreaskoepf**
- [x] VolumetricAveragePooling
- [x] VolumetricConvolution
- [x] VolumetricConvolutionMM
- [x] VolumetricFullConvolution
- [x] VolumetricMaxPooling
- [x] VolumetricMaxUnpooling
- [x] conversion of cuda modules (https://github.com/torch/cunn/pull/204)
- [x] cross-check with old implementation (via [xtest.lua](https://github.com/andreaskoepf/nn/blob/nn2/xtest.lua#L563))

(Additionally I changed the order of parameters of LookupTable_accGradParameters so that scale is the last parameter).

### CODE REVIEW

**Comment by soumith** [comment]
cc: @hughperkins

**Comment by hughperkins** [comment]
Wrt clnn, this is ready for merge.  clnn is volumetric-free, for the time being.

**Comment by soumith** [comment]
@andreaskoepf needs a rebase, now that I merged batch 4

**Comment by andreaskoepf** [comment]
rebased & ran cross check with old impl (for all modules but VolumetricMaxUnpooling since it very new), unit-tests pass.

**Pull request merged**
