### PR TITLE
Improve Volumetric shape checking.

### PR DESCRIPTION
**Pull request by gchanan**

### CODE REVIEW

**Comment by soumith** [comment]
looks good, cant merge this without the CUNN PR, or else cunn wont compile.

**Comment by gchanan** [comment]
The CUNN PR is now up at https://github.com/torch/cunn/pull/394.

**Comment by soumith** [comment]
this branch has a merge conflict now. can you do a quick rebase + push please. thanks.

**Comment by gchanan** [comment]
rebase done.

**Pull request merged**
