### PR TITLE
Improving whole documentation

### PR DESCRIPTION
**Pull request by Atcold**
Added diagrams and cleaned the example code and documentation

### CODE REVIEW

**Comment by Atcold** [comment]
Do not merge yet. Way more is coming!

**Comment by nicholas-leonard** [comment]
Nice.

**Comment by AjayTalati** [comment]
Helpful :+1:

**Comment by soumith** [comment]
pretty cool Atcold!

**Comment by AjayTalati** [comment]
The numbering on the `split table` doc looks funny, also should the output be a table of tables ?

**Comment by Atcold** [comment]
@AjayTalati, how do they look funny? I didn't get it :]

**Comment by soumith** [comment]
can you squash?

**Comment by Atcold** [comment]
I will squash, I will squash. But I have still half documentation to clean.
Shall we break down the cleaning in two parts?

**Comment by soumith** [comment]
sure.

**Comment by Atcold** [comment]
Done. Go, merge. I'll provide the second part as soon as I get some spare time (I've been kinda busy recently).

**Pull request merged**
