### PR TITLE
Remove return statement

### PR DESCRIPTION
**Pull request by lukemarris**
I think this line is causing problems.

### CODE REVIEW

**Comment by andresy** [comment]
what problem?

**Comment by lukemarris** [comment]
Sorry I made a mistake this is not breaking things but perhaps it is still inconsistent with the other modules?

**Comment by soumith** [comment]
@lukemarris This is correct behavior wrt lua 5.2 and forward. I can patch the other modules to follow this if you'd like.

**Comment by lukemarris** [comment]
@soumith No need. Thank you for the explanation.

**Pull request closed without merging**
