### PR TITLE
added support for tables as inputs to Concat

### PR DESCRIPTION
**Pull request by lukasc-ch**
1) added support for tables as inputs to Concat, 
2) removed some code redundancy (similar to ConcatTable)

### CODE REVIEW

**Comment by soumith** [comment]
hey Lucas, I wonder why you added table logic to nn.Concat, instead of using ConcatTable?

**Comment by lukasc-ch** [comment]
Hi @soumith 
ConcatTable and Concat have different functionality: ConcatTable adds the results of its children modules' outputs to a table, where Concat concatenates its children modules' output into a tensor along some dimension (i.e. different behavior on how to create the output). 
Before this PR, some functions of Concat start with self.gradInput:resizeAs(input). This is a problem in case of e.g. (not doing something useful, but minimal working example)
```
m = nn.Sequential()
    :add(nn.ConcatTable()
        :add(nn.Identity())
        :add(nn.Identity()))
    :add(nn.Concat(2)
        :add(nn.SelectTable(1))
        :add(nn.SelectTable(2)))
```
which would then crash during the backward call.

**Comment by fmassa** [comment]
I usually used `nn.ConcatTable` followed by `nn.JoinTable` in those situations. Is the merged `nn.Concat` in this PR more memory efficient than the two modules separately?

**Comment by lukasc-ch** [comment]
Hi Francisco
It should use the same amount of memory, but be more versatile. The above case could indeed be handled by ConcatTable and JoinTable, but consider
```
m = nn.Sequential()
    :add(nn.ConcatTable()
        :add(nn.Identity())
        :add(nn.Identity()))
    :add(nn.Concat(2)
        :add(nn.SelectTable(1))
        :add(nn.SelectTable(2))
        :add(nn.SelectTable(2)))
```
or more complex stuff with hierarchical tables
```
m = nn.Sequential()
    :add(nn.ConcatTable()
        :add(nn.Identity())
        :add(nn.ConcatTable()
            :add(nn.Identity())
            :add(nn.Identity()))
    :add(nn.ConcatTable()
        :add(nn.Concat(2)
            :add(nn.SelectTable(1))
            :add(nn.Sequential()
                :add(nn.SelectTable(2))
                :add(nn.SelectTable(1))))
         :add(nn.Sequential()
            :add(nn.SelectTable(2))
            :add(nn.SelectTable(2))))
```

**Comment by lukasc-ch** [comment]
Is there anything preventing this from getting merged? Is it still unclear what functionality is add by this PR / should I explain more?

**Comment by soumith** [comment]
thanks @lukasc-ch .

**Pull request merged**
