### PR TITLE
Removing initialization of output to fix #502

### LINKED ISSUE #502: New changes to nn.Identity break compatibility with previously saved models (and apparently, some other Torch code)
`nn.Identity`, as per commit b7a64bf1, has a new field `.tensorOutput` which does not exist in models checkpointed with previous versions. This causes issues loading these modules with the updated code.

Additionally, this update seems to be breaking code such as karpathy/char-rnn and karpathy/neuraltalk2. In char-rnn, for example, I am getting this error the first time `optim.rmsprop` is called:

```
/Users/jfsantos/torch/install/bin/luajit: /Users/jfsantos/torch/install/share/lua/5.1/nn/Identity.lua:13: bad argument #1 to 'set' (expecting number or Tensor or Storage at /tmp/luarocks_torch-scm-1-8315/torch7/generic/Tensor.c:1089)
stack traceback:
	[C]: in function 'set'
	/Users/jfsantos/torch/install/share/lua/5.1/nn/Identity.lua:13: in function 'func'
	...jfsantos/torch/install/share/lua/5.1/nngraph/gmodule.lua:252: in function 'neteval'
	...jfsantos/torch/install/share/lua/5.1/nngraph/gmodule.lua:287: in function 'forward'
	train.lua:270: in function 'opfunc'
	...s/jfsantos/torch/install/share/lua/5.1/optim/rmsprop.lua:32: in function 'rmsprop'
	train.lua:314: in main chunk
	[C]: in function 'dofile'
	...ntos/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x0103718320
```

### PR DESCRIPTION
**Pull request by jfsantos**
...as indicated by @soumith in the issue.

### CODE REVIEW

**Comment by soumith** [comment]
You need to do the same for gradInput right...

**Comment by jfsantos** [comment]
Yes, I will do that. But there are still some other issues which are breaking the CI tests:

```
ConcatTable
 Function call failed 
/home/travis/torch/install/share/lua/5.1/nn/Identity.lua:11: attempt to call field 'new' (a nil value)
stack traceback:

	/home/travis/torch/install/share/lua/5.1/nn/Identity.lua:11: in function 'backCompatibility'
	/home/travis/torch/install/share/lua/5.1/nn/Identity.lua:19: in function 'updateOutput'
	/home/travis/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function 'forward'
	/home/travis/torch/install/share/lua/5.1/nn/test.lua:3944: in function </home/travis/torch/install/share/lua/5.1/nn/test.lua:3908>

	[C]: in function 'xpcall'
	/home/travis/torch/install/share/lua/5.1/torch/Tester.lua:115: in function 'pcall'
	/home/travis/torch/install/share/lua/5.1/torch/Tester.lua:186: in function '_run'
	/home/travis/torch/install/share/lua/5.1/torch/Tester.lua:161: in function 'run'
	/home/travis/torch/install/share/lua/5.1/nn/test.lua:4770: in function 'test'
	(command line):1: in main chunk
	[C]: at 0x00406240
```
I'll take a look at those as well.

**Comment by soumith** [comment]
Ohhh, those are wrt table inputs. Sigh, we should just revert back to the old version until we write a more thought out fix.

**Comment by jfsantos** [comment]
Just figured that out! :)

**Pull request closed without merging**
