### PR TITLE
Add script that generates api_reference.md

### PR DESCRIPTION
**Pull request by apaszke**

### CODE REVIEW

**Comment by hughperkins** [comment]
Might be nice to see the generated documentation too?  Presumably that will be stored in the same repository?

**Comment by apaszke** [comment]
@hughperkins If you want to see how it looks now, you can take a look at [my fork](https://github.com/apaszke/nn/blob/master/lib/THNN/doc/api_reference.md).

**Comment by apaszke** [comment]
Uh, it appears the VolumetricMaxPooling somehow messes up the tests. But this PR has only changed .md files, so it should be safe to merge it.

**Comment by Atcold** [comment]
@apaszke, this script is just awesome! :+1:

**Comment by apaszke** [comment]
@soumith Again, repushed without changes. Tests are ok now :smile:

**Comment by soumith** [comment]
Thanks Adam!

**Pull request merged**
