### PR TITLE
replace the StochasticGradient example with optim example

### PR DESCRIPTION
**Pull request by hughperkins**
Address https://github.com/torch/torch7/issues/684

### CODE REVIEW

**Comment by soumith** [comment]
This is really nicely done! Thanks Hugh!

**Comment by hughperkins** [comment]
Thanks!  Seems there are a few typos and stuff, so I will fix those bit by bit...

**Comment by apaszke** [comment]
It might be a good place to mention that `:getParameters()` shares the memory with network, but it's actually rearranging everything under the hood it, so all old references are invalidated (and it's more like the network's parameters are views onto the parameter vector afterwards). It's often a source of confusion.

**Comment by hughperkins** [comment]
Updated, see: https://github.com/hughperkins/nn/blob/example-tweaks/doc/training.md#nn.traningneuralnet.dok

**Comment by Atcold** [comment]
Now the `optim` doc looks like this:
> # Optimization package
> This package contains several optimization routines and a logger for Torch:
> - Overview;
> - Optimization algorithms;
> - Logger.
You can add a 4th point
 - Example.

**Comment by Atcold** [comment]
@hughperkins, let me know if you don't have time. I can fix this overnight.
I need it for my class...

**Comment by soumith** [comment]
it seems better to teach users how to use optim, rather than nn.StochasticGradient.

**Comment by Atcold** [comment]
Yes, I'm covering that in my next class, as advanced material. Nevertheless, I believe we should restore the legacy documentation and, optionally, move the optim way in the `optim` documentation. We can even specify which is the suggested alternative, but removing doc is unacceptable, in my opinion.

Moreover,  with `StochasticGradient` you can train a network in 2 lines of code. `optim` requires much more code.

**Comment by hughperkins** [comment]
So....
- I made the change, because I was getting lots of issues on clnn where people were training a network, without batching, and were surprised when it didnt work/ran slowly, and they were basically doing stuff in a way quite differently from how eg I see Sergey and so on using it
- you do however make some good points, ie, you say:
  - optim doc should be in 'optim' repo, rather than 'nn' repo
  - probably not ideal to remove old doc
- I guess we can put the optim example into ... optim ... for now, and we can think about how to stretch something over the top somehow?  ie at a higher level than nn/optim, or perhaps just link to optim perhaps?

For your class, presumably you can link temporarily to the old location, ie:

https://github.com/torch/nn/blob/9f64ffa3e20c73ada3ab8c1564eb821e719f0155/doc/training.md#nn.traningneuralnet.dok

... so that we dont need to rush to change things, and your class works.

**Comment by hughperkins** [comment]
What I'll do for now is add the Training using StochasticGradient into the middle.  Is it good?  Well, I'll make a PR, and we can think about it?

**Comment by hughperkins** [comment]
https://github.com/torch/nn/pull/970

**Comment by hughperkins** [comment]
For migrating the optim example from nn to optim:
- optim-side pr: https://github.com/torch/optim/pull/134
- nn-side pr: https://github.com/torch/nn/pull/971

**Pull request merged**
