### PR TITLE
Volumteric Max-pooling now supports padding

### PR DESCRIPTION
**Pull request by kmul00**
This allows to provide **padding** in `VolumetricMaxPooling`

modified:   VolumetricMaxPooling.lua
modified:   generic/VolumetricMaxPooling.c
modified:   test.lua

**NOTE:** `VolumetricMaxUnpooling` still doesn't support **padded pooling**, though it will work for *pooling module without padding*. I will submit a *patch* for it soon.

### CODE REVIEW

**Comment by soumith** [comment]
thanks. will merge when there's a cunn equivalent.

**Comment by soumith** [comment]
this now has conflicts. could you please rebase.

**Comment by kmul00** [comment]
Is it okay now ?
I should `rebase` and `squash` the four commits right ?

**Comment by soumith** [comment]
ohh, you did git pull against torch/nn master. Instead, you should've done git pull --rebase

**Comment by soumith** [comment]
yea now you have to rebase and squash, but only rebase/squash your commits. i see other commits by me also in this PR now.

**Comment by kmul00** [comment]
I will close this PR and make a new one with the changes. Things got pretty messed up on my side (local git repo). Reason being, by inefficiency with git. Sorry about that.

I will pull the updated `nn` repo and apply my changes on top of that.

Once again, apologies if any inconvenience caused.

**Pull request closed without merging**
