### PR TITLE
nn.Replicate can now replicate across other dimensions than the first

### PR DESCRIPTION
**Pull request by egrefen**
This merge allows you to stack tensors across arbitrary dimensions, instead of just the first.

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
Looks like a good idea. Can you add unit tests and update the doc?

**Comment by soumith** [comment]
Same comments as nick ^^

**Comment by egrefen** [comment]
@soumith @nicholas-leonard Added docs and a simple unit test.

**Comment by egrefen** [comment]
@soumith @nicholas-leonard Fixed unit test bug. Updated Replicate to incorporate upstream changes.

**Comment by soumith** [comment]
thanks @egrefen , ready for merge. Can you squash your commits (git rebase -i and then git push --force) and I will merge it in.

**Comment by egrefen** [comment]
@soumith I ran those commands, although it doesn't seem to have done anything ("Everything up-to-date")

**Comment by egrefen** [comment]
Okay I'm going to start from scratch to roll all the changes into one commit. I'm don't know about all this rebase stuff.

**Pull request closed without merging**
