### PR TITLE
Update SoftMax to work in spatial mode

### PR DESCRIPTION
**Pull request by jhjin**
The module applies softmax in space and works both on a single
vector/matrix (1D/2D) or spatial vector/matrix (3D/4D).

### CODE REVIEW

**Comment by jhjin** [comment]
One concern is that the backend is similar to `nn.SoftMax` and mostly indexing is different. It might be redundant to keep this code along with `nn.SoftMax`.

**Comment by soumith** [comment]
@jhjin we could have a C implementation that is shared between SoftMax and SpatialSoftMax, and for the future, VolumetricSoftMax. If you send a PR at a later date to refactor that, I am happy to accept.

**Comment by jhjin** [comment]
@soumith thanks for the comment. will do that.

**Comment by soumith** [comment]
@jhjin found a bug. if the gradOutput is non-contiguous, you will get wrong results. Similar to how you added newContiguous for input, I suppose you could do the same with gradOutput

**Comment by jhjin** [comment]
@soumith I've updated the branch to reflect the non-contiguous gradOutput/output issue. Similar changes were made in `cunn` as well https://github.com/torch/cunn/pull/135

**Comment by soumith** [comment]
thanks a lot Jong!

**Comment by culurciello** [comment]
well done

**Pull request merged**
