### PR TITLE
Improve ClassNLLCriterion

### PR DESCRIPTION
**Pull request by adamlerer**
Moved ClassNLLCriterion to C. Normalization with weights is now done by the total weight of the minibatch, rather than its size

### CODE REVIEW

**Comment by soumith** [comment]
cc: @jonathantompson note that the normalization is changed to what was a more sensible way when using weights.

**Comment by jonathantompson** [comment]
Ahh. OK.  Would it be a better idea to have a flag for this new normalization scheme (rather than changing default behavior transparently)?

**Comment by soumith** [comment]
idk, it's up to you. the option was only recently added anyways right.

**Comment by soumith** [comment]
@jono do you really want me to introduce a flag for this normalization scheme? afaik only you are using this right, because it was recently introduced?

**Comment by jonathantompson** [comment]
Nah, it's OK. I'm sure no one else will care.

**Comment by soumith** [comment]
@jonathantompson thanks!

**Pull request merged**
