### PR TITLE
Migrate optim to optim

### PR DESCRIPTION
**Pull request by hughperkins**
This depends on https://github.com/torch/optim/pull/134 (should be merged as a pair)

### CODE REVIEW

**Comment by soumith** [comment]
Thanks Hugh!

**Comment by Atcold** [comment]
Is this commit bringing in also #970? I see the hash is the same: ef4ef6c.
Anyhow, thank you @hughperkins!

**Comment by hughperkins** [comment]
@Atcold yes, first commit added back stochasticgradient, second one moved optim doc to optim.

**Comment by Atcold** [comment]
@hughperkins, then what about #970? I'm confused.

**Comment by hughperkins** [comment]
> Edit: Oh, I see, you checked out hughperkins:migrate-optim-to-optim from hughperkins:add-back-stochasticgradient, so you inherited the previous commit.

Yes :-)  (otherwise there'd be lots of conflicts to deal with)

**Comment by Atcold** [comment]
Gotcha.

**Pull request merged**
